spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: TASK-SUBMISSION-SERVICE
          uri: lb://TASK-SUBMISSION-SERVICE
          predicates:
            - Path=/api/submissions/**,/submissions/**

        - id: TASK-SERVICE
          uri: lb://TASK-SERVICE
          predicates:
            - Path=/api/tasks/**,/tasks/**, /applicants/**

        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**,/users/**,/api/users/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

server:
  port: 5000

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/