spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
        routes:
          - id: USER-SERVICE
            uri: lb://USER-SERVICE
            predicates:
              - Path=/auth/**, /users/**, /api/users/**, /

          - id: TASK-SERVICE
            uri: lb://TASK-SERVICE
            predicates:
              - Path=/api/tasks/**, /tasks/**

          - id: TASK-SUBMISSION-SERVICE
            uri: lb://TASK-SUBMISSION-SERVICE
            predicates:
              - Path=/api/submissions/**, /submissions/**

        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        globalcors:
            cors-configuratgion:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods: "*"
                allowedHeaders: "*"

server:
  port: 5000

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/